### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by chechani** [acquia/mc-cs-plugin-custom-objects#275]
### Mautic Version

4.3.1

### PHP version

7.3

### What happened?

Downloaded and put in plugin directory with www-data user and group with 0755 permission recursively and from the front end, press button install and update plugins, this is the normal plugin installation process

what needs to do to install the custom objects plugin

### How can we reproduce this issue?

Step 1: Try to install

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Please see this forum thread for more guidance: https://forum.mautic.org/t/how-to-install-acquias-custom-objects-plugin/24204
