### ISSUE TITLE
Field from relationship type custom object does not work on segments

### ISSUE THREAD

**Issue by mzagmajster** [acquia/mc-cs-plugin-custom-objects#277]
### Mautic Version

4.2.x series

### PHP version

7.4.30

### What browsers are you seeing the problem on?

Firefox

### What happened?

I built two objects with this plugin: Object1 and Object2. Relevant Attributes are: Object1 (name) - master type, Object2 (paidAt) - relationship type.

I am able to link the object1 to leads and set the paidAt attribute via GUI, but when I try to use paidAt attribute and set the filters its like Mauitc is ignoring it. It only works properly if I use just the name of the Object1 in the filters.

I am running Mautic 4.4 (I am not able to select mautic 4.4 from the dropdown).

### How can we reproduce this issue?

Step 1: Create Master CO Object1
Step 2: Create Relationship CO Object2 with attribute paidAt
Step 3: Create two leads in the system.
Step 4: To lead1 you link custom item with name: "TestRecord", paidAt: 1970-01-01 00:00
Step 5: To lead2 you link custom item with name: "TestRecord", paidAt: 2022-07-17 13:00
Step 6: Create segment1 with filters:

Objec1.name equals "TestRecord"
Object2.paidAt equals 1970-01-01 00:00

Step 7: Create segment2 with filters:

Objec1.name equals "TestRecord"
Object2.paidAt grater than 1970-01-01 00:00

Step 8: Run php bin/console mautic:segments:update

Expected Result: lead1 is on segment1 and lead2 is on segment2

Actual Result: Both leads are on both segments.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
Try if you could use another master object instead of the relationship one. You can still link master objects with contacts or another objects. The relationship object is for specific use case and it is hidden from some places.

**Comment by mzagmajster** [comment]
@escopecz Approach you suggested works, so thanks for that.  What I am still curious about is: when exactly do we use relationship object type? 

I was also debugging segment queries and I can see that if the value is from relationship type object (datetime string below) query does not add filter for that object:

`[
  "cin_1ObjectId" => 1,  // Master Object Id
  "cin_1_value_value" => "MyTestObjectName",  // Master Object Name Value
  "cfwq_20_custom_field_id" => 20,  // Id of field (relationship type object) 
  "cfwq_20_value_value" => "1970-01-01 00:00",  // Datetime string for field from relationship type object
  "orpsegid" => 24  // Segment ID
]`

Maybe there is something I do not understand. but if we would also include relationship type object Id, filtering should work using relationship type object also.

**Comment by escopecz** [comment]
The relationship objects are meant as a relationship between the custom item and a contact and the relationship needs additional properties to it. Relationship objects are hidden from the menu and perhaps other places too. I suggest not to use them as it does not add any value. It was developed for specific use case and specific customer and it's a bit confusing for everyone else.

**Comment by mzagmajster** [comment]
I mean relationship type looked promssing for my situation too, but taped out with segments. Anyway I have decided to use master type objects for now.

Closing this issue in favor of workaround @escopecz suggested.

**Comment by adamchemiawppl** [comment]
> The relationship objects are meant as a relationship between the custom item and a contact and the relationship needs additional properties to it. Relationship objects are hidden from the menu and perhaps other places too. I suggest not to use them as it does not add any value. It was developed for specific use case and specific customer and it's a bit confusing for everyone else.

Would you mind to elaborate (or point me in right direction) on what it was intended to do exactly? I have a feeling it might be relevant to me, but without any info on topic it's difficult to figure out.

**Comment by escopecz** [comment]
Please play with it and see if it meets your use case. I'm not sure how to elaborate.
