### ISSUE TITLE
Mautic 4.4.4 support?

### ISSUE THREAD

**Issue by henrikwirth** [acquia/mc-cs-plugin-custom-objects#289]
### Mautic Version

4.4.4

### PHP version

8.0.25

### What happened?

See latest comment here: https://forum.mautic.org/t/how-to-install-acquias-custom-objects-plugin/24204/44

The Problem seems that the newest version of this plugin already runs on 5.x-alpha version of Mautic. Would it be possible to habe release tags in this project that match the Mautic versions it works for?

I'd really like to give this plugin a try, but couldn't get it working so far.

### How can we reproduce this issue?

Steps:
1. Install Latest stable mautic
2. Pull this plugin (latest versioon of default branch)
3. Run `mautic:plugins:install` 

### Relevant log output

```shell
HP Fatal error:  Uncaught Error: Interface 'Mautic\CoreBundle\Entity\UpsertInterface' not found in /var/www/ams/plugins/CustomObjectsBundle/Entity/CustomItem.php:45
Stack trace:
#0 /var/www/ams/vendor/composer/ClassLoader.php(571): include()
#1 /var/www/ams/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 [internal function]: spl_autoload_call()
#4 /var/www/ams/app/bundles/CoreBundle/DependencyInjection/Builder/Metadata/EntityMetadata.php(55): ReflectionClass->__construct()
#5 /var/www/ams/app/bundles/CoreBundle/DependencyInjection/Builder/BundleMetadataBuilder.php(164): Mautic\CoreBundle\DependencyInjection\Builder\Metadata\EntityMetadata->build()
#6 /var/www/ams/app/bundles/CoreBundle/DependencyInjection/Builder/BundleMetadataBuilder.php(158): Mautic\CoreBundle\DependencyInjection\Builder\BundleMetadataBuilder->buildMappings()
#7 /var/www/ams/app/bundles/CoreBundle/DependencyInjection/Builder/BundleMetadataBuilder.php(116): Mautic\Cor in /var/www/ams/plugins/CustomObjectsBundle/Entity/CustomItem.php on line 45
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by henrikwirth** [comment]
It seems, that the Tag 1.0.0 works for Mautic 4.x

- Are there any limitations or known bugs with this version and Mautic 4.x?
- Also would it be possible to document the mapping of versions?

**Comment by escopecz** [comment]
See https://forum.mautic.org/t/how-to-install-acquias-custom-objects-plugin/24204/49?u=escopecz
