### ISSUE TITLE
Wiki link on Github page is broken

### ISSUE THREAD

**Issue by PierreAmmeloot** [acquia/mc-cs-plugin-custom-objects#291]
### Mautic Version

4.2.x series

### PHP version

note relevant

### What browsers are you seeing the problem on?

Not relevant

### What happened?

On this page https://github.com/acquia/mc-cs-plugin-custom-objects wiki link (https://github.com/acquia/mc-cs-plugin-custom-objects/blob/staging/wiki) is broken.

### How can we reproduce this issue?

Step 1: 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
Thanks for the report! Do you think you could make a pull request with the correct link?

**Comment by PierreAmmeloot** [comment]
@escopecz I don't know the right link. Do you have it?

**Comment by PierreAmmeloot** [comment]
Is it this link (https://github.com/acquia/mc-cs-plugin-custom-objects/wiki) or another one?

**Comment by escopecz** [comment]
It's the one in the top bar menu:
![Screen Shot 2022-12-05 at 09 48 33](https://user-images.githubusercontent.com/1235442/205593811-90218487-5f51-4d89-a543-ea75bac9991c.png)

For me it goes to `https://github.com/acquia/mc-cs-plugin-custom-objects/wiki`

**Comment by npracht** [comment]
@escopecz you can close this issue (i don't have maintainer rights as on mautic/mautic)
