### ISSUE TITLE
How to add own unique identifier to custom object?

### ISSUE THREAD

**Issue by iparker** [acquia/mc-cs-plugin-custom-objects#311]
### Mautic Version

4.2.x series

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Chrome

### What happened?

Hello,

how can I create an custom object with an own unique identifiert?

In text and screenshots at [Custom objects — Acquia Docs](https://docs.acquia.com/campaign-studio/settings/custom-objects/#using-unique-identifiers) it looks like there is a way to define own unique identifier. But in my system there is no such option.

My use case is: I have to create and update custom objects via api but I don't want to store the custom object id in my system but set an existing id also for the custom object. 

How can I handle this?

### How can we reproduce this issue?

Step 1: XXX

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
Do you have the latest version of this plugin? See https://github.com/acquia/mc-cs-plugin-custom-objects/pull/278
